server:
  port: 65102

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    default-encoding: UTF-8
    host: mega.super.duper.pochta
    username: god
    password: passwordOfGod
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

logging.level:
  ru.yofik.mailservice: DEBUG