version: "3.8"

services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  bank:
    build: bank
    depends_on:
      - db
    ports:
      - "65101:65101"
  server:
    build: .
    depends_on:
      - db
    volumes:
      - ./deployments:/deployments
    ports:
      - "65100:65100"
