version: "3.8"

services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: .
    depends_on:
      - db
    ports:
      - "65100:65100"
