version: "3.8"

services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
